### ISSUE TITLE
Github action for tests passes even if the test fails

### ISSUE THREAD

**Issue by Ysajid** [sunnah-com/corrections#53]
The github action should fail if the tests do not pass.  
Check this run https://github.com/sunnah-com/corrections/pull/52/checks?check_run_id=1279000237, 2 of the tests fails but still the action is marked as passed.

This can be implemented by not using container for test, and directly installing in a python image instead.

Sample snippet for Gitlab CI/CD:

```yml
test:
  stage: test
  image: python:3.8
  tags:
    - docker
  services:
    - postgres:11
  variables:
    POSTGRES_DB: ci
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
    
  before_script:
    - pip install -r requirements/local.txt

  script:
    - coverage run -m pytest
    - coverage report

```
